# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('user_name', models.CharField(default='unkown_name', max_length=20)),
                ('kind', models.CharField(choices=[('python', 'python'), ('java', 'java')], default=('python', 'python'), max_length=20)),
            ],
        ),
    ]
